import type { NextPage } from "next";
import Head from "next/head";
import styles from "@/styles/Home.module.css";

import ResponsiveDrawer from "@/components/responsiveDrawer";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <ResponsiveDrawer title={"Dash Board"}>
          <main className={styles.main}>
            <h1 className={styles.title}>
              Welcome to <a href="https://nextjs.org">Dashboard!</a>
            </h1>
          </main>
        </ResponsiveDrawer>
      </div>
    </div>
  );
};

export default Home;
